### PR TITLE
support easyeffect 7.1.7

### LINKED ISSUE #18: Error: GSettings key last-used-output-preset not found in schema com.github.wwmm.easyeffects
I got the following error after upgrading `easyeffects` from `7.1.6` to `7.1.7`. This error will prevent the extension from displaying any input or output presets. They changed key names from `last-used-output-preset` to `last-loaded-output-preset`, and the same is for input. See https://github.com/wwmm/easyeffects/commit/6437bcb531c758ca16ce1fa3ae6ff08f336c5be0.
```
Error: GSettings key last-used-output-preset not found in schema com.github.wwmm.easyeffects
                                              
Stack trace:
  _checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:779:23
  createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:729:30
  getLastPresets@file:///home/remisiki/.local/share/gnome-shell/extensions/eepresetselector@ulville.github.io/extension.js:404:54
  _refreshMenu@file:///home/remisiki/.local/share/gnome-shell/extensions/eepresetselector@ulville.github.io/extension.js:289:50
  _init/<@file:///home/remisiki/.local/share/gnome-shell/extensions/eepresetselector@ulville.github.io/extension.js:73:22
  @resource:///org/gnome/shell/ui/init.js:21:20
```

### PR DESCRIPTION
**Pull request by akiyiwen**
closes #18

### CODE REVIEW

**Comment by ulville** [comment]
Thanks for informing me about the change #18  and for the fix. But blindly changing the key names will break the extension for the users who are still on the older versions and will stay so for a while (users of native package for easyeffects on fixed release distros). Also we need to handle the flatpak easyeffects the same way. (your fix only changes the key names for native package)

Checking the version of EasyEffects comes to mind first but somehow it doesn't seem to be possible. I tried `easyeffects --version` in terminal but it doesn't output anything. I searched through the gjs api references to find a way to check an app's version but no luck. 

Other options are
1. Check the GSettings Sceme Keys and check which of our key names are there.
2. Use a try-catch statement. Try one of the keys, if it fails try the other one.

Option 1 feels more like the right way to me. I also did my research and test, here is how we get the keys for a specified settings scheme using Gio:

```js
const settings = new Gio.Settings({
    schema_id: 'com.github.wwmm.easyeffects',
});
let settingsSchema = settings.settings_schema
let keys = settingsSchema.list_keys(); // Array of strings
```

then we can check which kind of keys are in the keys array and use the ones we have. 

For flatpak we can't access its GSettings object directly but we use gsettings command running inside its flatpak sandbox to get values we need. We can do the same to get the keys. Normally the command is `gsettings list-keys com.github.wwmm.easyeffects`. But for flatpak it becomes `flatpak run --command=/usr/bin/gsettings com.github.wwmm.easyeffects list-keys com.github.wwmm.easyeffects`. Here is how we can do it in our code:

```js
let getKeysCommand = [
    'flatpak',
    'run',
    '--command=/usr/bin/gsettings', // command we want to run instead of easyeffects
    'com.github.wwmm.easyeffects', // inside easyeffects' flatpak sandbox
    'list-keys', // argument 1
    'com.github.wwmm.easyeffects', // argument 2
];
let keys = await this.execCommunicate(getKeysCommand); // String (values are seperated by new line)
``` 

As a similar approach we can check which kind of key names are in there and use the ones we have.

If you can work on the implementation and update the PR I'll wait, otherwise tell me so I can close this PR and implement it myself

**Comment by ulville** [comment]
We may not need to implement the check logic for the flatpak tho. For the time being it's still at 7.1.6 on Flathub. But probably it'll be updated to 7.1.7 soon. And when it happens practically everyone using the flatpak version will be fine. It's probably fine to just change the key names in https://github.com/ulville/eepresetselector/blob/11786ff8e9714c4e2da60519071cadf6a20d8503/eepresetselector%40ulville.github.io/extension.js#L391 and https://github.com/ulville/eepresetselector/blob/11786ff8e9714c4e2da60519071cadf6a20d8503/eepresetselector%40ulville.github.io/extension.js#L396

**Comment by akiyiwen** [comment]
Thanks for your information @ulville, I agree that a simple renaming is not a good solution and can break the extension for users still using older versions of `easyeffects`. Yes, option 1 should be a better workaround for now, so I implemented a schema key validation block that should be working for both version `7.1.7` and versions before.

I was using native installation of `easyeffects` so I did not notice the change still not took place for `flatpak` users, and now I have tested the new code on both native and `flatpak` platform.

**Comment by ulville** [comment]
Great! The code looks good to me. And you've already tested it on both of the versions , much better! Thank you for your contribution! 👍👍👍👍👍

**Pull request merged**
